Fix everything with the files so the tests will pass
crypto-browserify/crypto-browserify pull request #199
Opened 2021-01-24 13:33 UTC by coltongit

This PR may be a big one, but all build tests should now pass just fine.

2021-01-24 13:53 UTC, coltongit commented
This PR also requires Node 10+. Builds ran using Node 10/11 should pass OK, as long as saucelabs is configured correctly here

2021-01-24 16:04 UTC, ljharb requested changes

2021-01-24 16:04 UTC, ljharb commented
Requiring node 10+ is a breaking change that is best avoided, especially for a bundler polyfill like this one.

2021-01-24 16:16 UTC, coltongit commented on index.js
> +const algos = require('browserify-sign/algos')
standard is indeed forcing this else the travis builds will fail

2021-01-24 16:20 UTC, coltongit commented
Superseding this PR with a new one.

2021-01-24 16:20 UTC, closed without merging

2021-01-24 16:25 UTC, ljharb commented on index.js
> +const algos = require('browserify-sign/algos')
Seems easier to just repurpose this PR :-)

2021-01-24 17:51 UTC, coltongit commented on index.js
> +const algos = require('browserify-sign/algos')
Too much work put in to not supersede this PR, so better to just supersede it instead.

2021-01-24 18:01 UTC, ljharb commented on index.js
> +const algos = require('browserify-sign/algos')
ok, not sure i understand that - you can just start over and force push to the same branch.

2021-02-02 14:07 UTC, coltongit commented
This PR has been superseded by PR #200.